FROM node:20.9.0-alpine3.17

WORKDIR /app

COPY package*.json ./

RUN npm i

COPY src ./src
COPY public ./public
COPY tsconfig.json ./tsconfig.json
COPY *.config.js ./
COPY *.config.mjs ./
COPY tailwind.config.ts ./tailwind.config.ts
COPY postcss.config.mjs ./postcss.config.mjs

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL ${NEXT_PUBLIC_API_URL}

ARG JWT_PUBLIC_KEY
ENV JWT_PUBLIC_KEY ${JWT_PUBLIC_KEY}

RUN npm run build

CMD npm start