version: '3.9'

services:
  mamiepierre-database:
    image: postgres:latest
    restart: 'no'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mamiepierre
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d mamiepierre']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5435:5432
    expose:
      - 5432
    volumes:
      - mamiepierre-database:/var/lib/postgresql/data

  mamiepierre-server:
    depends_on:
      mamiepierre-database:
        condition: service_healthy
    build: './server'
    ports:
      - 4000:4000
    volumes:
      - ./server/src:/app/src

  mamiepierre-upload-service:
    build: file-upload-service
    ports:
      - 8000:8000
    volumes:
      - ./file-upload-service/files:/app/files

volumes:
  mamiepierre-database:
