FROM node:20.9.0-alpine3.17

RUN apk --no-cache add curl
RUN apk add make g++ python3 git
RUN npm i -g node-pre-gyp

RUN mkdir /app
WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm i

COPY src src
COPY tsconfig.json tsconfig.json
COPY prisma prisma

RUN npx prisma generate

# tanspile TS into JS for perf
RUN ["npm", "run", "build"]

# the command that starts our app
CMD ["npm", "run", "start:prod"]
